#include "TlsCertificateGenerator.h"
#include "Logger.h"

#include <QDir>
#include <QFile>
#include <QFileInfo>
#include <QProcess>
#include <QStandardPaths>
#include <QUuid>

TlsCertificateGenerator::Result TlsCertificateGenerator::generateSelfSignedCert(
    const QString& certDir, const QString& commonName)
{
    Result result;

    QDir().mkpath(certDir);

    QString certPath = certDir + QStringLiteral("/netshare_cert.pem");
    QString keyPath = certDir + QStringLiteral("/netshare_key.pem");

    QFile::remove(certPath);
    QFile::remove(keyPath);

    {
        QStringList args = {
            QStringLiteral("req"),
            QStringLiteral("-x509"),
            QStringLiteral("-newkey"),
            QStringLiteral("rsa:4096"),
            QStringLiteral("-nodes"),
            QStringLiteral("-keyout"), keyPath,
            QStringLiteral("-out"), certPath,
            QStringLiteral("-sha256"),
            QStringLiteral("-days"), QStringLiteral("3650"),
            QStringLiteral("-subj"),
            QStringLiteral("/CN=%1/O=NetShare/OU=AutoGenerated").arg(commonName),
            QStringLiteral("-addext"),
            QStringLiteral("subjectAltName=DNS:localhost,DNS:*.local,IP:127.0.0.1,IP:::1")
        };

        if (!runOpenSSL(args)) {
            result.errorMessage = QStringLiteral("Failed to generate self-signed certificate via OpenSSL");
            LOG_ERROR("%s", qPrintable(result.errorMessage));
            QFile::remove(keyPath);
            return result;
        }
    }

    if (!QFileInfo::exists(certPath) || !QFileInfo::exists(keyPath)) {
        result.errorMessage = QStringLiteral("Certificate files were not created after OpenSSL commands");
        LOG_ERROR("%s", qPrintable(result.errorMessage));
        return result;
    }

    result.success = true;
    result.certPath = certPath;
    result.keyPath = keyPath;

    LOG_INFO("Self-signed TLS certificate generated successfully:");
    LOG_INFO("  Certificate: %s", qPrintable(certPath));
    LOG_INFO("  Private key: %s", qPrintable(keyPath));

    return result;
}

bool TlsCertificateGenerator::certificatesExist(const QString& certDir)
{
    return QFileInfo::exists(certDir + QStringLiteral("/netshare_cert.pem")) &&
           QFileInfo::exists(certDir + QStringLiteral("/netshare_key.pem"));
}

QString TlsCertificateGenerator::defaultCertDir()
{
    return QDir::toNativeSeparators(
        QStandardPaths::writableLocation(QStandardPaths::AppConfigLocation) +
        QStringLiteral("/certs"));
}

QString TlsCertificateGenerator::defaultCertPath()
{
    return defaultCertDir() + QStringLiteral("/netshare_cert.pem");
}

QString TlsCertificateGenerator::defaultKeyPath()
{
    return defaultCertDir() + QStringLiteral("/netshare_key.pem");
}

bool TlsCertificateGenerator::runOpenSSL(const QStringList& args)
{
    QProcess process;
    process.setProgram(QStringLiteral("openssl"));
    process.setArguments(args);
    process.setProcessChannelMode(QProcess::MergedChannels);

    LOG_DEBUG("Running OpenSSL: openssl %s", qPrintable(args.join(' ')));

    process.start();
    if (!process.waitForStarted(5000)) {
        LOG_ERROR("Failed to start OpenSSL process: %s",
                  qPrintable(process.errorString()));
        return false;
    }

    if (!process.waitForFinished(30000)) {
        LOG_ERROR("OpenSSL process timed out");
        process.kill();
        return false;
    }

    if (process.exitCode() != 0) {
        QString output = QString::fromUtf8(process.readAllStandardOutput());
        LOG_ERROR("OpenSSL failed (exit code %d): %s",
                  process.exitCode(), qPrintable(output));
        return false;
    }

    return true;
}
